language: node_js
node_js: node
cache: yarn
branches:
  only:
  - master
  - /^greenkeeper/.*$/
addons:
  code_climate:
    repo_token: d8d04f10e1e84541a1b7b15ca5d9c3db46a6d99c2299d8a5bd0c1edffc75870d
after_success:
  - yarn global add codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
notifications:
  slack: notifme:MJIOAvkBeUE4bs34W2H9sgaR
